#!/usr/bin/env bash
# This script is displaying numbers from 1 - 100
#	together with fizz, fizzbuss
#	using conditional statements


i=1
while [ $i -le 100 ]
do
	if (($i % 15 == 0))
	then
		echo "FizzBuzz"
	elif (($i % 3 == 0))
	then
		echo "Fizz"
	elif (($i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i+1))	
done
